Teste Walmart/BancoTeste/app/Stingy.Web/Controllers/ContaController.cs
using Stingy.Dominio.ContratoServicoAplicacao;
using Stingy.Dominio.Entidades;
using Stingy.Web.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Stingy.Web.Controllers
{
    public class ContaController : Controller
    {
        private readonly IContaServicoAplicacao _contaServicoAplicacao;

        public ContaController(IContaServicoAplicacao ContaServicoAplicacao)
        {
            _contaServicoAplicacao = ContaServicoAplicacao;
        }

        public ActionResult Index()
        {
            var contas = _contaServicoAplicacao.Recuperar();
            var model = contas.Select(x => new ContaViewModel()
                                               {
                                                   Id = x.Id,
                                                   Agencia = x.Agencia,
                                                   NumeroConta = x.NumeroConta,
                                                   Saldo = x.Saldo.ToString()
                                               });
            return View(model);
        }

        #region Criar Conta

        public ActionResult Criar()
        {
            var model = new ContaViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Criar(ContaViewModel model)
        {
            try
            {
                _contaServicoAplicacao.Salvar(new Conta(model.NumeroConta, model.Agencia, Convert.ToDecimal(model.Saldo)));

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(model);
            }
        }

        #endregion

        #region Editar Conta

        public ActionResult Editar(int id)
        {
            var conta = _contaServicoAplicacao.Recuperar(id);
            var model = new ContaViewModel()
            {
                Id = conta.Id,
                NumeroConta = conta.NumeroConta,
                Agencia = conta.Agencia,
                Saldo = conta.Saldo.ToString()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(int id, ContaViewModel model)
        {
            try
            {
                var conta = _contaServicoAplicacao.Recuperar(id);
                conta.AdicionarAgencia(model.Agencia);
                conta.AdicionarNumeroConta(model.NumeroConta);
                conta.PreencherSaldo(Convert.ToDecimal(model.Saldo));

                _contaServicoAplicacao.Salvar(conta);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(model);
            }
        }

        #endregion

        #region Remover Conta

        public ActionResult Deletar(int id)
        {
            try
            {
                _contaServicoAplicacao.Excluir(_contaServicoAplicacao.Recuperar(id));

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }

        #endregion




    }
}

Teste Walmart/BancoTeste/app/Stingy.Web/Controllers/TransacoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Stingy.Dominio.ContratoServicoAplicacao;
using Stingy.Dominio.Entidades;
using Stingy.Web.Models;

namespace Stingy.Web.Controllers
{
    public class TransacoesController : Controller
    {
        private readonly ITransacoesServicoApliacao _transacoesServicoAplicacao;
        private readonly IContaServicoAplicacao _contaServicoAplicacao;

        public TransacoesController(ITransacoesServicoApliacao TransacoesServicoAplicacao, IContaServicoAplicacao contaServicoAplicacao)
        {
            _transacoesServicoAplicacao = TransacoesServicoAplicacao;
            _contaServicoAplicacao = contaServicoAplicacao;
        }



        public ActionResult Index()
        {
            var transacoes = _transacoesServicoAplicacao.Recuperar();
            var model = transacoes.Select(x => new TransacoesViewModel()
                                                   {
                                                       Id = x.Id,
                                                       DataTransacao = x.DataTransacao.ToShortDateString(),
                                                       Valor = x.Valor.ToString(),
                                                       TipoTransacao = x.TipoTransacao,
                                                       ContaOrigem = ObterConta(x.ContaOrigem),
                                                       ContaDestino = x.ContaDestino == null
                                                                     ? new ContaViewModel() : ObterConta(x.ContaDestino)
                                                   });

            return View(model);
        }


        public ActionResult Saque()
        {
            var model = new TransacoesViewModel
                            {
                                ContasOrigem = ObterContas()
                            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Saque(TransacoesViewModel model)
        {
            try
            {
                _transacoesServicoAplicacao.Saque(model.IdContaOrigem, Convert.ToDecimal(model.Valor));
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.msg = ex.Message;
            }

            model.ContasOrigem = ObterContas();
            return View(model);
        }

        public ActionResult Transferencia()
        {
            var model = new TransacoesViewModel
            {
                ContasOrigem = ObterContas()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Transferencia(TransacoesViewModel model)
        {
            try
            {
                _transacoesServicoAplicacao.Transferencia(model.IdContaOrigem, model.IdContaDestino, Convert.ToDecimal(model.Valor));
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                ViewBag.msg = ex.Message;
            }

            model.ContasOrigem = ObterContas();
            return View(model);
        }


        #region Metodos Privados

        private ContaViewModel ObterConta(Conta conta)
        {
            return new ContaViewModel
            {
                Id = conta.Id,
                Agencia = conta.Agencia,
                NumeroConta = conta.NumeroConta,
                Saldo = conta.Saldo.ToString()
            };
        }

        private List<ContaViewModel> ObterContas()
        {
            var contas = _contaServicoAplicacao.Recuperar();
            return contas.Select(ObterConta).ToList();
        }
        #endregion

    }
}

Teste Walmart/BancoTeste/app/Stingy.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>My MVC Application</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Criar Conta", "Criar", "Conta")</li>
                    <li>@Html.ActionLink("Efetuar Saque", "Saque", "Transacoes")</li>
                    <li>@Html.ActionLink("Efetuar Transferencia", "Transferencia", "Transacoes")</li>
                    <li>@Html.ActionLink("Listar transações", "Index", "Transacoes")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </nav>
            
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

Teste Walmart/BancoTeste/app/Stingy.Web/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}

Teste Walmart/BancoTeste/app/Stingy.Web/Views/Shared/_MiniCarrinho.cshtml
@model Stingy.Dominio.ObjetoDeValor.CarrinhoDeCompra
<a href="@Url.Action("Listar", "CarrinhoDeCompra")"><span class="destaque valor">@Model.ValorTotal.ToString("c")</span>(<span
    class="quantidade">@Model.Items.Sum(x => x.Quantidade)</span> itens)</a> 